apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: first-react
  namespace: react-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: react
        module: demo
        env: react-demo
    spec:
      containers:
      - name: first-react
        image: ccr.ccs.tencentyun.com/boilwater/react:IMAGE_VERSION
      imagePullSecrets:
      - name: tencentccrsecret
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: react
    module: demo
    env: react-demo
  name: first-react
  namespace: react-demo
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
  type: NodePort
  selector:
    app: react
    module: demo
    env: react-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: first-react
  namespace: react-demo
spec:
  rules:
  - host: www.boilwater.cn
    http:
      paths:
      - path: /bruce
        backend:
          serviceName: first-react
          servicePort: 80